#CROSS=/home/mef/iMX6/fsl-release-bsp/build-dfb/tmp/sysroots/x86_64-linux/usr/bin/cortexa9hf-vfp-neon-poky-linux-gnueabi/arm-poky-linux-gnueabi-

BINARES=bin

ifdef CROSS
ARCH := armv7l
else
ARCH := $(shell uname -m)
endif
USER := $(shell whoami)

CC=${CROSS}gcc
LD=${CROSS}ld
AR=${CROSS}ar
SO=${CROSS}gcc -shared
STRIP=${CROSS}strip

CFLAGS = -c -Wall

INSTALL_DIR = ../${BINARES}/${USER}/${ARCH}
TARGET=root@192.168.11.145:/home/root


