CROSS=/home/mef/iMX6/fsl-release-bsp/build-dfb/tmp/sysroots/x86_64-linux/usr/bin/cortexa9hf-vfp-neon-poky-linux-gnueabi/arm-poky-linux-gnueabi-

ifdef CROSS
ARCH := armv7l
else
ARCH := $(shell uname -m)
endif
USER := $(shell whoami)

CC=${CROSS}gcc
LD=${CROSS}ld
AR=${CROSS}ar
SO=${CROSS}gcc -shared
STRIP=${CROSS}strip

CFLAGS = -c -Wall

BINARES=bin
INCLUDE_DIR=${TOP}/include/
LIB_DIR=${TOP}/lib/
INSTALL_DIR = ${TOP}/${BINARES}/${USER}/${ARCH}

#debian
#TARGET=root@192.168.1.7:/root
#yocto
TARGET=root@192.168.1.7:/home/root
TARGET_LIB=root@192.168.1.7:/usr/lib


